# Blogo — 开发环境日志配置
logger:
  debug: true
  level: "debug"
  console: true
  caller_skip: 1

  file:
    enable: false

  access_log:
    enable: false

  error_log:
    enable: false

  audit_log:
    enable: false

  security_log:
    enable: false

  hooks:
    - enable: true
      level: "info"
      type: "gorm"
      max_buffer: 1024
      max_thread: 4
      options:
        debug: "false"
        db_type: "mysql"
        dsn: "${DB_DSN}"
        max_open_conn: "16"
        max_idle_conn: "4"
        max_life_time: "86400"
        max_idle_time: "7200"
