// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wirex

import (
	"context"
	"github.com/zhian9/blogo-server/internal/mods"
	"github.com/zhian9/blogo-server/internal/mods/blog"
	api2 "github.com/zhian9/blogo-server/internal/mods/blog/api"
	biz2 "github.com/zhian9/blogo-server/internal/mods/blog/biz"
	dal2 "github.com/zhian9/blogo-server/internal/mods/blog/dal"
	"github.com/zhian9/blogo-server/internal/mods/blog/msg"
	"github.com/zhian9/blogo-server/internal/mods/rbac"
	"github.com/zhian9/blogo-server/internal/mods/rbac/api"
	"github.com/zhian9/blogo-server/internal/mods/rbac/biz"
	"github.com/zhian9/blogo-server/internal/mods/rbac/dal"
)

// Injectors from injector_wire.go:

// NewInjector 使用 Google Wire 生成依赖注入实现。
// 它会组装：DB、Cache、Auth 以及业务模块 Mods（包含 RBAC 与 Blog）。
func NewInjector(ctx context.Context) (*Injector, func(), error) {
	db, cleanup, err := InitDB(ctx)
	if err != nil {
		return nil, nil, err
	}
	cacher, cleanup2, err := InitCacher(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	auther, cleanup3, err := InitAuth(ctx)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	trans := ProvideTrans(db)
	menu := &dal.Menu{
		DB: db,
	}
	menuResource := &dal.MenuResource{
		DB: db,
	}
	roleMenu := &dal.RoleMenu{
		DB: db,
	}
	bizMenu := &biz.Menu{
		Cache:           cacher,
		Trans:           trans,
		MenuDAL:         menu,
		MenuResourceDAL: menuResource,
		RoleMenuDAL:     roleMenu,
	}
	apiMenu := &api.Menu{
		MenuBIZ: bizMenu,
	}
	role := &dal.Role{
		DB: db,
	}
	userRole := &dal.UserRole{
		DB: db,
	}
	bizRole := &biz.Role{
		Cache:       cacher,
		Trans:       trans,
		RoleDAL:     role,
		RoleMenuDAL: roleMenu,
		UserRoleDAL: userRole,
	}
	apiRole := &api.Role{
		RoleBIZ: bizRole,
	}
	user := &dal.User{
		DB: db,
	}
	bizUser := &biz.User{
		Cache:       cacher,
		Trans:       trans,
		UserDAL:     user,
		UserRoleDAL: userRole,
	}
	apiUser := &api.User{
		UserBIZ: bizUser,
	}
	client := ProvideCaptchaRedisClient()
	service, err := ProvideCaptchaService(client)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	operationLog := &dal.OperationLog{
		DB: db,
	}
	login := &biz.Login{
		Cache:           cacher,
		Auth:            auther,
		UserDAL:         user,
		UserRoleDAL:     userRole,
		MenuDAL:         menu,
		UserBIZ:         bizUser,
		CaptchaSvc:      service,
		OperationLogDAL: operationLog,
	}
	apiLogin := &api.Login{
		LoginBIZ: login,
	}
	logger := &dal.Logger{
		DB: db,
	}
	bizLogger := &biz.Logger{
		LoggerDAL: logger,
	}
	apiLogger := &api.Logger{
		LoggerBIZ: bizLogger,
	}
	bizOperationLog := &biz.OperationLog{
		OperationLogDAL: operationLog,
	}
	apiOperationLog := &api.OperationLog{
		OperationLogBIZ: bizOperationLog,
	}
	userFollow := &dal.UserFollow{
		DB: db,
	}
	bizUserFollow := &biz.UserFollow{
		DB:            db,
		Trans:         trans,
		UserFollowDAL: userFollow,
		UserDAL:       user,
	}
	apiUserFollow := &api.UserFollow{
		UserFollowBIZ: bizUserFollow,
	}
	casbinx := rbac.NewCasbinx(cacher, menu, menuResource, role)
	rbacRBAC := &rbac.RBAC{
		DB:              db,
		MenuAPI:         apiMenu,
		RoleAPI:         apiRole,
		UserAPI:         apiUser,
		LoginAPI:        apiLogin,
		LoggerAPI:       apiLogger,
		OperationLogAPI: apiOperationLog,
		FollowAPI:       apiUserFollow,
		Casbinx:         casbinx,
		OperationLogBIZ: bizOperationLog,
	}
	article := &dal2.Article{
		DB: db,
	}
	category := &dal2.Category{
		DB: db,
	}
	tag := &dal2.Tag{
		DB: db,
	}
	articleTag := &dal2.ArticleTag{
		DB: db,
	}
	comment := &dal2.Comment{
		DB: db,
	}
	articleVisibleUser := &dal2.ArticleVisibleUser{
		DB: db,
	}
	contribution := &dal2.Contribution{
		DB: db,
	}
	articlePermission := &biz2.ArticlePermission{
		ArticleVisibleUserDAL: articleVisibleUser,
	}
	subscriber := &dal2.Subscriber{
		DB: db,
	}
	mailWorker := msg.NewMailWorker(subscriber)
	bizArticle := &biz2.Article{
		Trans:                 trans,
		ArticleDAL:            article,
		CategoryDAL:           category,
		TagDAL:                tag,
		ArticleTagDAL:         articleTag,
		CommentDAL:            comment,
		ArticleVisibleUserDAL: articleVisibleUser,
		ContributionDAL:       contribution,
		ArticlePermission:     articlePermission,
		MailWorker:            mailWorker,
	}
	apiArticle := &api2.Article{
		ArticleBIZ: bizArticle,
	}
	bizCategory := &biz2.Category{
		Trans:       trans,
		CategoryDAL: category,
		ArticleDAL:  article,
	}
	apiCategory := &api2.Category{
		CategoryBIZ: bizCategory,
	}
	bizTag := &biz2.Tag{
		Trans:         trans,
		TagDAL:        tag,
		ArticleDAL:    article,
		ArticleTagDAL: articleTag,
	}
	apiTag := &api2.Tag{
		TagBIZ: bizTag,
	}
	project := &dal2.Project{
		DB: db,
	}
	bizComment := &biz2.Comment{
		Trans:      trans,
		CommentDAL: comment,
		ArticleDAL: article,
		ProjectDAL: project,
	}
	apiComment := &api2.Comment{
		CommentBIZ: bizComment,
	}
	page := &dal2.Page{
		DB: db,
	}
	bizPage := &biz2.Page{
		Trans:   trans,
		PageDAL: page,
	}
	apiPage := &api2.Page{
		PageBIZ: bizPage,
	}
	friendLink := &dal2.FriendLink{
		DB: db,
	}
	bizFriendLink := &biz2.FriendLink{
		Trans:         trans,
		FriendLinkDAL: friendLink,
	}
	apiFriendLink := &api2.FriendLink{
		FriendLinkBIZ: bizFriendLink,
	}
	setting := &dal2.Setting{
		DB: db,
	}
	bizSetting := &biz2.Setting{
		Trans:      trans,
		SettingDAL: setting,
	}
	apiSetting := &api2.Setting{
		SettingBIZ: bizSetting,
	}
	notification := &dal2.Notification{
		DB: db,
	}
	bizNotification := &biz2.Notification{
		Trans:           trans,
		NotificationDAL: notification,
		UserDAL:         user,
	}
	apiNotification := &api2.Notification{
		NotificationBIZ: bizNotification,
	}
	image := &dal2.Image{
		DB: db,
	}
	bizImage := &biz2.Image{
		Trans:    trans,
		ImageDAL: image,
	}
	apiImage := &api2.Image{
		ImageBIZ: bizImage,
	}
	statistics := &dal2.Statistics{
		DB: db,
	}
	bizStatistics := &biz2.Statistics{
		DB:            db,
		Trans:         trans,
		StatisticsDAL: statistics,
	}
	apiStatistics := &api2.Statistics{
		StatisticsBIZ: bizStatistics,
	}
	articleLike := &dal2.ArticleLike{
		DB: db,
	}
	bizArticleLike := &biz2.ArticleLike{
		Trans:          trans,
		ArticleLikeDAL: articleLike,
		ArticleDAL:     article,
	}
	apiArticleLike := &api2.ArticleLike{
		ArticleLikeBIZ: bizArticleLike,
	}
	articleFavorite := &dal2.ArticleFavorite{
		DB: db,
	}
	bizArticleFavorite := &biz2.ArticleFavorite{
		Trans:              trans,
		ArticleFavoriteDAL: articleFavorite,
		ArticleDAL:         article,
	}
	apiArticleFavorite := &api2.ArticleFavorite{
		ArticleFavoriteBIZ: bizArticleFavorite,
	}
	profile := &biz2.Profile{
		ArticleDAL:         article,
		ArticleLikeDAL:     articleLike,
		ArticleFavoriteDAL: articleFavorite,
		CommentDAL:         comment,
		ContributionDAL:    contribution,
		UserDAL:            user,
		UserFollowDAL:      userFollow,
	}
	apiProfile := &api2.Profile{
		ProfileBIZ: profile,
	}
	seo := &api2.SEO{
		ArticleBIZ: bizArticle,
	}
	bizSubscriber := &biz2.Subscriber{
		SubscriberDAL: subscriber,
		Trans:         trans,
		MailWorker:    mailWorker,
	}
	apiSubscriber := &api2.Subscriber{
		SubscriberBIZ: bizSubscriber,
	}
	projectTag := &dal2.ProjectTag{
		DB: db,
	}
	projectVisibleUser := &dal2.ProjectVisibleUser{
		DB: db,
	}
	projectTimeline := &dal2.ProjectTimeline{
		DB: db,
	}
	projectResource := &dal2.ProjectResource{
		DB: db,
	}
	projectLike := &dal2.ProjectLike{
		DB: db,
	}
	projectFavorite := &dal2.ProjectFavorite{
		DB: db,
	}
	projectPermission := &biz2.ProjectPermission{
		ProjectVisibleUserDAL: projectVisibleUser,
	}
	bizProject := &biz2.Project{
		Trans:                 trans,
		ProjectDAL:            project,
		CategoryDAL:           category,
		TagDAL:                tag,
		ProjectTagDAL:         projectTag,
		CommentDAL:            comment,
		ProjectVisibleUserDAL: projectVisibleUser,
		ProjectTimelineDAL:    projectTimeline,
		ProjectResourceDAL:    projectResource,
		ProjectLikeDAL:        projectLike,
		ProjectFavoriteDAL:    projectFavorite,
		ContributionDAL:       contribution,
		ProjectPermission:     projectPermission,
	}
	apiProject := &api2.Project{
		ProjectBIZ: bizProject,
	}
	bizProjectLike := &biz2.ProjectLike{
		Trans:          trans,
		ProjectLikeDAL: projectLike,
		ProjectDAL:     project,
	}
	apiProjectLike := &api2.ProjectLike{
		ProjectLikeBIZ: bizProjectLike,
	}
	bizProjectFavorite := &biz2.ProjectFavorite{
		Trans:              trans,
		ProjectFavoriteDAL: projectFavorite,
		ProjectDAL:         project,
	}
	apiProjectFavorite := &api2.ProjectFavorite{
		ProjectFavoriteBIZ: bizProjectFavorite,
	}
	bizProjectTimeline := &biz2.ProjectTimeline{
		Trans:              trans,
		ProjectTimelineDAL: projectTimeline,
		ProjectDAL:         project,
	}
	apiProjectTimeline := &api2.ProjectTimeline{
		ProjectTimelineBIZ: bizProjectTimeline,
	}
	bizProjectResource := &biz2.ProjectResource{
		Trans:              trans,
		ProjectResourceDAL: projectResource,
		ProjectDAL:         project,
	}
	apiProjectResource := &api2.ProjectResource{
		ProjectResourceBIZ: bizProjectResource,
	}
	blogBlog := &blog.Blog{
		DB:                 db,
		ArticleAPI:         apiArticle,
		CategoryAPI:        apiCategory,
		TagAPI:             apiTag,
		CommentAPI:         apiComment,
		PageAPI:            apiPage,
		FriendLinkAPI:      apiFriendLink,
		SettingAPI:         apiSetting,
		NotificationAPI:    apiNotification,
		ImageAPI:           apiImage,
		StatisticsAPI:      apiStatistics,
		ArticleLikeAPI:     apiArticleLike,
		FavoriteAPI:        apiArticleFavorite,
		ProfileAPI:         apiProfile,
		SEOAPI:             seo,
		SubscriberAPI:      apiSubscriber,
		MailWorker:         mailWorker,
		ProjectAPI:         apiProject,
		ProjectLikeAPI:     apiProjectLike,
		ProjectFavoriteAPI: apiProjectFavorite,
		ProjectTimelineAPI: apiProjectTimeline,
		ProjectResourceAPI: apiProjectResource,
	}
	modsMods := &mods.Mods{
		RBAC: rbacRBAC,
		Blog: blogBlog,
	}
	injector := &Injector{
		DB:    db,
		Cache: cacher,
		Auth:  auther,
		M:     modsMods,
	}
	return injector, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
